import Head from "next/head";
import { useState } from "react";
import AnimalView from "../Components/AnimalView";
import Header from "../Components/Header";
import SearchBar from "../Components/SearchBar";

export default function Home({ animals }) {
  const [search, setSearch] = useState("");

  const allAnimals = animals.filter((animal) =>
    animal.name.toLowerCase().includes(search.toLowerCase())
  );

  const handleChange = (e) => {
    e.preventDefault();

    setSearch(e.target.value.toLowerCase());
  };

  return (
    <div className="">
      <Head>
        <title>Animal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <SearchBar onChange={handleChange} />

      <AnimalView animals={allAnimals} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const animals = await fetch(
    "https://60d075407de0b20017108b89.mockapi.io/api/v1/animals"
  ).then((res) => res.json());

  return {
    props: {
      animals,
    },
  };
}
